<a href="https://colab.research.google.com/github/balamurali9492/Python_class1/blob/main/8_Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy Retail Analytics Assignment **

**Business Scenario**

**You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.**

**Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.**

**You are provided with two main NumPy arrays:**

**1.sales_data — monthly sales revenue generated by each store for different product categories.**

**2.cost_data — total cost incurred by each store for the same product categories.**


# **Part 1: Dataset Creation**

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([

    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([

    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


# **Part 2: Basic Array Understanding**

In [ ]:
# Question 1: Array Dimensions
# The finance manager wants to confirm how many stores and product categories are present in the data.

# Write NumPy code to display:

# Number of dimensions in sales_data
# Shape of sales_data
# Total number of values
# Data type of the array
# Memory occupied by the array

print("Number of dimensions:", sales_data.ndim)
print("Shape:", sales_data.shape)
print("Total number of values:", sales_data.size)
print("Data type:", sales_data.dtype)
print("Memory occupied:", sales_data.nbytes, "bytes")

Number of dimensions: 2
Shape: (5, 6)
Total number of values: 30
Data type: int64
Memory occupied: 240 bytes


In [ ]:
# Question 2: Store and Category Count
# Calculate the following:

# Total number of stores
# Total number of product categories
# Total number of store-category combinations

total_stores = len(stores)
total_categories = len(categories)
total_combinations = sales_data.size

print("Total number of stores:", total_stores)
print("Total number of product categories:", total_categories)
print("Total store-category combinations:", total_combinations)

Total number of stores: 5
Total number of product categories: 6
Total store-category combinations: 30


In [ ]:
# Question 3: Sales Data Type Conversion
# The reporting application requires sales values in floating-point format.

# Convert sales_data into:

# float32
# float64
# Compare the memory used by both arrays.

sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)

print("float32 data type:", sales_float32.dtype)
print("float64 data type:", sales_float64.dtype)

print("float32 memory:", sales_float32.nbytes, "bytes")
print("float64 memory:", sales_float64.nbytes, "bytes")

float32 data type: float32
float64 data type: float64
float32 memory: 120 bytes
float64 memory: 240 bytes


# Part 3: Indexing and Data Extraction

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([

    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([

    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

In [ ]:
# Question 4: Bengaluru Store Analysis
# The Bengaluru regional manager wants to review sales for all product categories.

# Extract and display the complete sales row for Bengaluru.

bengaluru_sales = sales_data[0]

print("Bengaluru sales:")
print(bengaluru_sales)

Bengaluru sales:
[850000 420000 310000 275000 190000 225000]


In [ ]:
# Question 5: Mumbai Cost Analysis
# Extract the total cost incurred by the Mumbai store for all product categories.

mumbai_cost = cost_data[3]
total_cost = np.sum(mumbai_cost)

print("Mumbai cost for all categories:", total_cost)

Mumbai cost for all categories: 2065000


In [ ]:
# Question 6: Electronics Sales Across Stores
# The electronics department wants to compare its sales performance across all five stores.

# Extract the Electronics sales column from sales_data.

electronics_sales = sales_data[:, 0]

print("Electronics sales across all stores:")
print(electronics_sales)

Electronics sales across all stores:
[ 850000  780000  920000 1050000  690000]


In [ ]:
# Question 7: Clothing Cost Across Stores
# Extract the Clothing cost for every store from cost_data.

clothing_cost = cost_data[:, 2]

print("Clothing cost across all stores:")
print(clothing_cost)

In [ ]:
# Question 8: Hyderabad Furniture Performance
# Find the following for Hyderabad:

# Furniture sales
# Furniture cost
# Furniture profit

# Hyderabad is row index 1
# Furniture is column index 3

hyderabad_furniture_sales = sales_data[1, 3]
hyderabad_furniture_cost = cost_data[1, 3]
hyderabad_furniture_profit = (hyderabad_furniture_sales - hyderabad_furniture_cost)

print("Hyderabad Furniture Sales:", hyderabad_furniture_sales)
print("Hyderabad Furniture Cost:", hyderabad_furniture_cost)
print("Hyderabad Furniture Profit:", hyderabad_furniture_profit)

Hyderabad Furniture Sales: 310000
Hyderabad Furniture Cost: 225000
Hyderabad Furniture Profit: 85000


In [ ]:
# Question 9: Chennai Category Range
# Extract Chennai’s sales for the following categories:

# Groceries
# Clothing
# Furniture
# Use array slicing.

# Chennai is row index 2
# Groceries, Clothing and Furniture are columns 1 to 3

chennai_sales = sales_data[2, 1:4]

print("Chennai sales for Groceries, Clothing and Furniture:")
print(chennai_sales)

Chennai sales for Groceries, Clothing and Furniture:
[390000 340000 260000]


In [ ]:
# Question 10: Selected Store Analysis
# Extract sales data for:

# Bengaluru
# Chennai
# Pune

# Include only:

# Electronics
# Clothing
# Beauty
# Use advanced indexing.

stores = [0, 2, 4]
categories = [0, 2, 4]

selected_rows = np.take(sales_data, stores, axis=0)
selected_sales = np.take(selected_rows, categories, axis=1)

print("Selected Store Sales:")
print(selected_sales)

Selected Store Sales:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


# Part 4: Sales Aggregation

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([

    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([

    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print(sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([

    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([

    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

In [ ]:
# Question 11: Company-Wide Sales
# Calculate the total sales revenue generated by all stores and all categories.

import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([

    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([

    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

total_sales = np.sum(sales_data)

print("Total company-wide sales:", total_sales)

Total company-wide sales: 11675000


In [ ]:
# Question 12: Store-Wise Sales
# Calculate total sales revenue for each store.

# Display the result together with the store names.

# Expected output format:

# Bengaluru: total sales
# Hyderabad: total sales
# Chennai: total sales
# Mumbai: total sales
# Pune: total sales

store_sales = np.sum(sales_data, axis=1)

for store, total in zip(stores, store_sales):
    print(store, ":", total)

Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000
Pune : 1980000


In [ ]:
# Question 13: Category-Wise Sales
# Calculate total sales for each product category across all stores.

# Display each category name with its total sales.

category_sales = np.sum(sales_data, axis=0)

for category, total in zip(categories, category_sales):
    print(category, ":", total)

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Beauty : 1010000
Sports : 1175000


In [ ]:
# Question 14: Average Sales Per Store
# Calculate the average sales generated by each store across all six product categories.

average_sales = np.mean(sales_data, axis=1)

for store, average in zip(stores, average_sales):
    print(store, ":", average)

Bengaluru : 378333.3333333333
Hyderabad : 382500.0
Chennai : 385000.0
Mumbai : 470000.0
Pune : 330000.0


In [ ]:
# Question 15: Average Sales Per Category
# Calculate the average sales of each product category across the five stores.

average_category_sales = np.mean(sales_data, axis=0)

for category, average in zip(categories, average_category_sales):
    print(category, ":", average)

Electronics : 858000.0
Groceries : 437000.0
Clothing : 320000.0
Furniture : 283000.0
Beauty : 202000.0
Sports : 235000.0


In [ ]:
# Question 16: Highest-Selling Store
# Identify:

# Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store
# Use np.argmax().

store_totals = np.sum(sales_data, axis=1)

highest_index = np.argmax(store_totals)
highest_store = stores[highest_index]
highest_sales = store_totals[highest_index]

print("Index:", highest_index)
print("Store:", highest_store)
print("Total Sales:", highest_sales)

Index: 3
Store: Mumbai
Total Sales: 2820000


In [ ]:
# Question 17: Lowest-Selling Store
# Identify the store with the lowest overall sales.

# Use np.argmin().

store_totals = np.sum(sales_data, axis=1)

lowest_index = np.argmin(store_totals)
lowest_store = stores[lowest_index]
lowest_sales = store_totals[lowest_index]

# Display the results
print("Index:", lowest_index)
print("Store:", lowest_store)
print("Total Sales:", lowest_sales)

store_totals = np.sum(sales_data, axis=1)
lowest_index = np.argmin(store_totals)
print(stores[lowest_index], ":", store_totals[lowest_index])

Index: 4
Store: Pune
Total Sales: 1980000
Pune : 1980000


In [ ]:
# Question 18: Highest-Selling Category
# Find the product category that generated the highest total sales across the company.


category_totals = np.sum(sales_data, axis=0)

highest_index = np.argmax(category_totals)

highest_category = categories[highest_index]
highest_sales = category_totals[highest_index]

print("Highest-Selling Category:", highest_category)
print("Total Sales:", highest_sales)

Highest-Selling Category: Electronics
Total Sales: 4290000


In [ ]:
# Question 19: Lowest-Selling Category
# Find the product category with the lowest total sales across all stores.

category_totals = np.sum(sales_data, axis=0)

lowest_index = np.argmin(category_totals)
lowest_category = categories[lowest_index]

lowest_sales = category_totals[lowest_index]

print("Lowest-Selling Category:", lowest_category)
print("Total Sales:", lowest_sales)

Lowest-Selling Category: Beauty
Total Sales: 1010000


# Part 5: Cost Analysis

In [ ]:
# Question 20: Total Company Cost
# Calculate the total cost incurred by SmartMart across all stores and product categories.

total_cost = np.sum(cost_data)

print("Total Company Cost:", total_cost)

Total Company Cost: 8600000


In [ ]:
# Question 21: Store-Wise Cost
# Calculate the total cost incurred by each store.

store_cost = np.sum(cost_data, axis=1)
for store, cost in zip(stores, store_cost):
    print(store, ":", cost)

Bengaluru : 1665000
Hyderabad : 1685000
Chennai : 1710000
Mumbai : 2065000
Pune : 1475000


In [ ]:
# Question 22: Category-Wise Cost
# Calculate the total cost incurred for each product category across all stores.

category_cost = np.sum(cost_data, axis=0)
for category, cost in zip(categories, category_cost):
    print(category, ":", cost)

Electronics : 3250000
Groceries : 1660000
Clothing : 1145000
Furniture : 1045000
Beauty : 665000
Sports : 835000


In [ ]:
# Question 23: Most Expensive Store
# Identify the store with the highest total operating cost.

store_cost = np.sum(cost_data, axis=1)

highest_index = np.argmax(store_cost)
highest_store = stores[highest_index]

highest_cost = store_cost[highest_index]

print("Most Expensive Store:", highest_store)
print("Total Operating Cost:", highest_cost)

Most Expensive Store: Mumbai
Total Operating Cost: 2065000


In [ ]:
# Question 24: Lowest-Cost Store
# Identify the store with the lowest total cost.

store_cost = np.sum(cost_data, axis=1)

lowest_index = np.argmin(store_cost)
lowest_store = stores[lowest_index]

lowest_cost = store_cost[lowest_index]

print("Lowest-Cost Store:", lowest_store)
print("Total Cost:", lowest_cost)

Lowest-Cost Store: Pune
Total Cost: 1475000


In [ ]:
# Question 25: Most Expensive Product Category
# Determine which product category has the highest total cost across all stores.

category_cost = np.sum(cost_data, axis=0)

highest_index = np.argmax(category_cost)
highest_category = categories[highest_index]

highest_cost = category_cost[highest_index]

print("Most Expensive Product Category:", highest_category)
print("Total Cost:", highest_cost)

Most Expensive Product Category: Electronics
Total Cost: 3250000


# Part 6: Profit Analysis Using Two Arrays

In [ ]:
# Question 26: Profit Matrix
# Calculate the profit generated for every store and product category.

# Use:

# profit_data = sales_data - cost_data
# Display the complete profit matrix.

profit_data = sales_data - cost_data

print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [ ]:
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [ ]:
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [ ]:
# Question 27: Store-Wise Profit
# Calculate the total profit generated by each store.

store_profit = np.sum(profit_data, axis=1)

for store, profit in zip(stores, store_profit):
    print(store, ":", profit)

Bengaluru : 605000
Hyderabad : 610000
Chennai : 600000
Mumbai : 755000
Pune : 505000


In [ ]:
# Question 28: Category-Wise Profit
# Calculate the total profit generated by each product category.

category_profit = np.sum(profit_data, axis=0)

for category, profit in zip(categories, category_profit):
    print(category, ":", profit)

In [ ]:
# Question 29: Most Profitable Store
# Identify the store that generated the highest total profit.

# Display:

# Store name
# Total sales
# Total cost
# Total profit

import numpy as np
store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)

highest_index = np.argmax(store_profit)

highest_store = stores[highest_index]

print("Most Profitable Store name:", highest_store)
print("Total Sales:", store_sales[highest_index])
print("Total Cost:", store_cost[highest_index])
print("Total Profit:", store_profit[highest_index])

Most Profitable Store name: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000


In [ ]:
# Question 30: Least Profitable Store
# Identify the store that generated the lowest total profit.

store_profit = np.sum(profit_data, axis=1)

lowest_index = np.argmin(store_profit)

lowest_store = stores[lowest_index]
lowest_profit = store_profit[lowest_index]

print("Least Profitable Store:", lowest_store)
print("Total Profit:", lowest_profit)

Least Profitable Store: Pune
Total Profit: 505000


In [ ]:
# Question 31: Most Profitable Category
# Find the category with the highest total profit across all stores.
import numpy as np

category_profit = np.sum(profit_data, axis=0)

highest_index = np.argmax(category_profit)

highest_category = categories[highest_index]

highest_profit = category_profit[highest_index]

print("Most Profitable Category:", highest_category)
print("Total Profit:", highest_profit)

Most Profitable Category: Electronics
Total Profit: 1040000


In [ ]:
# Question 32: Least Profitable Category
# Find the category with the lowest total profit.


category_profit = np.sum(profit_data, axis=0)

lowest_index = np.argmin(category_profit)

lowest_category = categories[lowest_index]

lowest_profit = category_profit[lowest_index]

print("Least Profitable Category:", lowest_category)
print("Total Profit:", lowest_profit)

In [ ]:
# Question 33: Maximum Individual Profit
# Find the highest profit generated by any single store-category combination.

# Display:

# Profit amount
# Store name
# Product category
# Use np.unravel_index().

index = np.unravel_index(np.argmax(profit_data), profit_data.shape)

print("Profit:", profit_data[index])
print("Store:", stores[index[0]])
print("Category:", categories[index[1]])

Profit: 260000
Store: Mumbai
Category: Electronics


In [ ]:
# Question 34: Minimum Individual Profit
# Find the smallest profit generated by a store-category combination.

# Display the corresponding store and category.

# Find the position of the minimum profit
index = np.unravel_index(np.argmin(profit_data), profit_data.shape)

# Display the result
print("Minimum Profit:", profit_data[index])
print("Store:", stores[index[0]])
print("Category:", categories[index[1]])

Minimum Profit: 55000
Store: Pune
Category: Furniture


# Part 7: Profit Margin Analysis

In [4]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([

    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([

    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

profit_data = sales_data - cost_data

print("Profit Matrix:")
print(profit_data)


Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [5]:
# Question 35: Profit Margin Matrix
# Calculate the profit margin percentage for every store-category combination.

# Use:

# profit_margin = (profit_data / sales_data) * 100
# Round the result to two decimal places.


profit_data = sales_data - cost_data

profit_margin = np.round((profit_data / sales_data) * 100, 2)

print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [6]:
# Question 36: Store-Wise Profit Margin
# Calculate the overall profit margin percentage for each store using:

# Store Profit Margin =
# Total Store Profit / Total Store Sales × 100

store_profit = profit_data.sum(axis=1)
store_sales = sales_data.sum(axis=1)

store_profit_margin = np.round((store_profit / store_sales) * 100, 2)

print(store_profit_margin)

[26.65 26.58 25.97 26.77 25.51]


In [ ]:
# Question 37: Category-Wise Profit Margin
# Calculate the overall profit margin percentage for each product category.

category_profit = profit_data.sum(axis=0)
category_sales = sales_data.sum(axis=0)

category_profit_margin = np.round((category_profit / category_sales) * 100, 2)

print(category_profit_margin)

In [7]:
# Question 38: Best Store by Profit Margin
# Identify the store with the highest overall profit margin.

best_store_index = np.argmax(store_profit_margin)
best_store = stores[best_store_index]

print(best_store)

Mumbai


In [13]:
# Question 39: Best Category by Profit Margin
# Identify the product category with the highest profit margin.

best_category_index = np.argmax(category_profit_margin)
best_category = categories[best_category_index]

print(best_category)

Beauty


In [23]:
# Question 40: Low-Margin Transactions
# Management considers a profit margin below 22% to be weak.

# Find all store-category combinations where the profit margin is below 22%.

# Display:

# Store
# Category
# Sales
# Cost
# Profit
# Profit margin
# Use Boolean indexing.

# Calculate profit margin
# profit_margin = (profit_data / sales_data) * 100

profit_margin = (profit_data / sales_data) * 100

low_margin_mask = profit_margin < 22

store_idx, category_idx = np.where(low_margin_mask)

if len(store_idx) == 0:
    print("No store-category combinations found with profit margin below 22%.")
else:
  for i, j in zip(store_idx, category_idx):
   store_name = stores[i]
   category_name = categories[j]
   sales = sales_data[i,j]
   cost = cost_data[i, j]
   profit = profit_data[i, j]
   profit_margin = round(profit_margin[i, j],2)

   print(f"\nStore: {store_name}")
   print(f"Category: {category_name}")
   print(f"  Sales: {sales}")
   print(f"  Cost: {cost}")
   print(f"  Profit: {profit}")
   print(f"  Profit Margin: {profit_margin:.2f}%")

No store-category combinations found with profit margin below 22%.


# Part 8: Boolean Filtering

In [24]:
# Question 41: High Sales Values
# Find all sales values greater than ₹5,00,000.

# Boolean mask for sales greater than ₹5,00,000
high_sales = sales_data[sales_data > 500000]

print("Sales values greater than ₹5,00,000:")
print(high_sales)

Sales values greater than ₹5,00,000:
[ 850000  780000  920000 1050000  510000  690000]


In [26]:
# Question 42: Low Sales Values
# Find all sales values below ₹2,00,000.

low_sales = sales_data[sales_data < 200000]

print("Sales values below ₹2,00,000:")
print(low_sales)

Sales values below ₹2,00,000:
[190000 185000 175000]


In [29]:
# Question 43: High Profit Values
# Find all store-category combinations where profit is greater than ₹1,50,000.

profit = profit_data > 150000
index = np.argwhere(profit)

for i, j in index:
    print(f"Store: {stores[i]}")
    print(f"Category: {categories[j]}")
    print(f"Profit: ₹{profit_data[i, j]}\n")

Store: Bengaluru
Category: Electronics
Profit: ₹210000

Store: Hyderabad
Category: Electronics
Profit: ₹190000

Store: Chennai
Category: Electronics
Profit: ₹220000

Store: Mumbai
Category: Electronics
Profit: ₹260000

Store: Pune
Category: Electronics
Profit: ₹160000



In [30]:
# Question 44: Moderate Sales Range
# Find sales values between ₹2,50,000 and ₹5,00,000.

# Use np.logical_and().

sales_mask = np.logical_and(sales_data >= 250000, sales_data <= 500000)
moderate_sales = sales_data[sales_mask]

print(moderate_sales)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [32]:
# Question 45: Premium Performance
# A store-category combination is considered premium when:

# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.

premium_mask = np.logical_and(sales_data > 500000, profit_data > 150000)

for i, j in np.argwhere(premium_mask):
    print(f"Store: {stores[i]}, Category: {categories[j]}, Sales: {sales_data[i,j]}, Profit: {profit_data[i,j]}")

Store: Bengaluru, Category: Electronics, Sales: 850000, Profit: 210000
Store: Hyderabad, Category: Electronics, Sales: 780000, Profit: 190000
Store: Chennai, Category: Electronics, Sales: 920000, Profit: 220000
Store: Mumbai, Category: Electronics, Sales: 1050000, Profit: 260000
Store: Pune, Category: Electronics, Sales: 690000, Profit: 160000


In [33]:
# Question 46: Underperforming Combinations
# A store-category combination is considered underperforming when:

# Sales are below ₹2,50,000
# Profit margin is below 25%
# Find all such combinations.

profit_margin = (profit_data / sales_data) * 100
underperforming = np.logical_and(sales_data < 250000, profit_margin < 25)

for i, j in np.argwhere(underperforming):
    print(f"Store: {stores[i]}, Category: {categories[j]}, Sales: ₹{sales_data[i,j]}, Profit Margin: {profit_margin[i,j]:.2f}%")

Store: Pune, Category: Furniture, Sales: ₹225000, Profit Margin: 24.44%


In [35]:
# Question 47: Category Performance Classification
# Create a new array that classifies every sales value as:

# "High" when sales are at least ₹5,00,000
# "Medium" when sales are between ₹2,50,000 and ₹4,99,999
# "Low" when sales are below ₹2,50,000
# Use np.where() or np.select().

conditions = [sales_data >= 500000, sales_data >= 250000]
choices = ["High", "Medium"]

performance_classification = np.select(conditions, choices, default="Low")

print(performance_classification)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


# Part 9: Target-Based Analysis

In [36]:
# Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])


In [39]:
# Question 48: Target Comparison
# Compare every store’s category sales against sales_targets.

# Use NumPy broadcasting.

target_status = sales_data >= sales_targets
print(target_status)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [40]:
# Question 49: Target Achievement Matrix
# Create a Boolean array where:

# True means the store achieved the category target
# False means the store failed to achieve the target

target_achievement = sales_data >= sales_targets
print(target_achievement)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [42]:
# Question 50: Target Achievement Count
# Calculate the number of categories in which each store achieved its target.

target_achievement = sales_data >= sales_targets
target_count = target_achievement.sum(axis=1)

print(target_count)

[1 4 2 6 0]


In [52]:
# Question 51: Best Target-Performing Store
# Find the store that achieved the highest number of category targets.

best_store_index = np.argmax(target_count)
best_store = stores[best_store_index]

print("Best Target-Performing Store:",best_store)
print("Targets Achieved:", target_count[best_store_index])

Best Target-Performing Store: Mumbai
Targets Achieved: 6


In [44]:
# Question 52: Target Achievement by Category
# Calculate how many stores achieved the target for each product category.

target_achievement = sales_data >= sales_targets
category_target_count = target_achievement.sum(axis=0)

print(category_target_count)

[3 2 2 2 2 2]


In [53]:
# Question 53: Sales Target Variance
# Calculate the difference between actual sales and target sales for every store.

# Use:

# Variance = Actual Sales - Target Sales

sales_variance = sales_data - sales_targets
print(sales_variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [54]:
# Question 54: Percentage Above or Below Target
# Calculate the percentage variance from the target using:

# Percentage Variance =
# (Actual Sales - Target Sales) / Target Sales × 100

percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100
percentage_variance = np.round(percentage_variance, 2)

print(percentage_variance)

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


In [55]:
# Question 55: Stores Missing Electronics Target
# Identify stores that failed to achieve the Electronics sales target.

electronics_target = sales_data[:, 0] < sales_targets[0]
failed_stores = stores[electronics_target]

print(failed_stores)

['Hyderabad' 'Pune']


In [58]:
# Question 56: Stores Achieving All Targets
# Check whether any store achieved its target in all six product categories.

# Use np.all().

target_achievement = sales_data >= sales_targets
all_targets = np.all(target_achievement, axis=1)
store_name = stores[np.all(target_achievement, axis=1)]

print(all_targets)
print(store_name)

[False False False  True False]
['Mumbai']


In [59]:
# Question 57: Stores Achieving At Least One Target
# Identify stores that achieved at least one category target.

# Use np.any().

target_achievement = sales_data >= sales_targets
stores_with_target = stores[np.any(target_achievement, axis=1)]

print(stores_with_target)

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


# Part 10: Discount Scenario

In [61]:
# SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

print(discount_rates)

[0.1  0.05 0.15 0.12 0.08 0.1 ]


In [62]:
# Question 58: Discount Amount Matrix
# Calculate the discount amount for each store-category combination.

# Use broadcasting.

discount_amount = sales_data * discount_rates
print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [63]:
# Question 59: Sales After Discount
# Calculate the net sales value after applying the category-wise discounts.

net_sales = sales_data - discount_amount
print(net_sales)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [64]:
# Question 60: Profit After Discount
# Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

profit_after_discount = net_sales - cost_data
print(profit_after_discount)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [65]:
# Question 61: Profit Margin After Discount
# Calculate the new profit margin after applying discounts.

profit_margin_after_discount = (profit_after_discount / net_sales) * 100
profit_margin_after_discount = np.round(profit_margin_after_discount, 2)

print(profit_margin_after_discount)

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


In [67]:
# Question 62: Loss-Making Transactions
# Check whether any store-category combination becomes loss-making after discounts.

# Display the affected store and category names.

loss_mask = profit_after_discount < 0

for i, j in np.argwhere(loss_mask):
    print(f"Store: {stores[i]}, Category: {categories[j]}, Loss:, {profit_after_discount[i, j]}")

In [71]:
# Question 63: Discount Impact
# Calculate how much total revenue the company loses because of the proposed discounts.

total_revenue_loss = np.sum(discount_amount)

print(f"Total revenue lost: ₹{total_revenue_loss:,.2f}")

Total revenue lost: ₹1,146,350.00


In [72]:
# Question 64: Store Most Affected by Discounts
# Identify the store that loses the highest amount of revenue due to discounts.

store_discount =  np.sum(discount_amount, axis = 1)

print(stores[np.argmax(store_discount)])

Mumbai


# Part 11: Tax and Price Adjustment

In [74]:
# The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

print(tax_rates)

[0.18 0.05 0.12 0.18 0.18 0.12]


In [78]:
# Question 65: Tax Collection Matrix
# Calculate the tax collected on sales for each store and category.

tax_collected = sales_data * tax_rates
print(tax_collected)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [79]:
# Question 66: Sales Including Tax
# Calculate the final customer billing value after adding tax.

sales_with_tax = sales_data + tax_collected
print(sales_with_tax)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [80]:
# Question 67: Store-Wise Tax Collection
# Calculate the total tax collected by each store.

store_tax = np.sum(tax_collected, axis=1)
print(store_tax)

[321900. 321200. 331800. 401400. 274650.]


In [81]:
# Question 68: Category-Wise Tax Collection
# Calculate total tax collected for each category.

category_tax = np.sum(tax_collected, axis=0)
print(category_tax)

[772200. 109250. 192000. 254700. 181800. 141000.]


In [82]:
# Question 69: Highest Tax-Contributing Store
# Identify the store that contributes the highest tax amount.

highest_tax_store = stores[np.argmax(store_tax)]
print(highest_tax_store)

Mumbai


# Part 12: Array Modification

In [88]:
# Question 70: Updated Pune Electronics Sales
# The Pune store reports that its Electronics sales were entered incorrectly.

# Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

# Make the change in a copied array without modifying the original array.

updated_sales = sales_data.copy()
updated_sales[4, 0] = 740000

print(updated_sales)

#print(sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


In [89]:
# Question 71: Revised Beauty Cost
# Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

# Create an updated cost array.

updated_cost = cost_data.copy()
updated_cost[:, 4] = updated_cost[:, 4] * 0.92

print(updated_cost)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


In [90]:
# Question 72: Furniture Cost Increase
# Furniture costs increase by 12% for all stores.

# Update only the Furniture column.

updated_cost[:, 3] = updated_cost[:, 3] * 1.12
print(updated_cost)

[[640000 315000 220000 229600 115000 160000]
 [590000 350000 210000 252000 128800 170000]
 [700000 295000 245000 218400 110400 155000]
 [790000 390000 265000 280000 151800 205000]
 [530000 310000 205000 190400 105800 145000]]


In [92]:
# Question 73: Store Closure Simulation
# Assume the Pune store is temporarily closed.

# Remove Pune’s sales and cost data from the analysis using np.delete().

sales_without_pune = np.delete(sales_data, 4, axis=0)
cost_without_pune = np.delete(cost_data, 4, axis=0)

print("Sales without Pune:")
print(sales_without_pune)
print("cost without Pune:")
print(cost_without_pune)

Sales without Pune:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
cost without Pune:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [97]:
# Question 74: Adding a New Store
# A new Delhi store is opened with the following data:

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

# Add Delhi to both arrays using np.vstack().

# Also add "Delhi" to the stores array.


sales_updated = np.vstack((sales_data, delhi_sales))
cost_updated = np.vstack((cost_data, delhi_cost))
stores_updated = np.append(stores, "Delhi")

print("Stores updated:")
print(stores_updated)
print("\nSales updated:")
print(sales_updated)
print("\nCost updated:")
print(cost_updated)

Stores updated:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']

Sales updated:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]

Cost updated:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


In [98]:
# Question 75: Adding a New Product Category
# SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

# Add the new category as a column using np.column_stack() or np.hstack().


sales_updated = np.column_stack((sales_data, home_appliance_sales))
cost_updated = np.column_stack((cost_data, home_appliance_cost))

print("Sales updated:")
print(sales_updated)
print("\ncost updated:")
print(cost_updated)

Sales updated:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]

cost updated:
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


# Part 13: Sorting and Ranking

In [99]:
# Question 76: Sort Stores by Sales
# Sort stores in ascending order based on total sales.

# Display store names and sales totals.

total_sales = sales_data.sum(axis=1)
order = np.argsort(total_sales)

for i in order:
    print(stores[i], total_sales[i])

Pune 1980000
Bengaluru 2270000
Hyderabad 2295000
Chennai 2310000
Mumbai 2820000


In [101]:
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [100]:
# Question 77: Rank Stores by Profit
# Rank stores from highest to lowest total profit.

# Use np.argsort().

total_profit = np.sum(profit_data, axis=1)
order = np.argsort(total_profit)[::-1]

for i in order:
    print(stores[i], total_profit[i])

Mumbai 755000
Hyderabad 610000
Bengaluru 605000
Chennai 600000
Pune 505000


In [102]:
print(sales_data)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


In [104]:
# Question 78: Sort Categories by Revenue
# Sort product categories from highest to lowest total revenue.

category_revenue = np.sum(sales_data, axis=0)
order = np.argsort(category_revenue)[::-1]

for i in order:
    print(categories[i], category_revenue[i])

Electronics 4290000
Groceries 2185000
Clothing 1600000
Furniture 1415000
Sports 1175000
Beauty 1010000


In [105]:
# Question 79: Top Three Store-Category Sales
# Find the three highest individual sales values in the complete sales matrix.

# Display their:

# Sales value
# Store name
# Category name

flat_indices = np.argsort(sales_data.ravel())[-3:][::-1]

for idx in flat_indices:
    i, j = np.unravel_index(idx, sales_data.shape)
    print(f"Sales: ₹{sales_data[i,j]}, Store: {stores[i]}, Category: {categories[j]}")

Sales: ₹1050000, Store: Mumbai, Category: Electronics
Sales: ₹920000, Store: Chennai, Category: Electronics
Sales: ₹850000, Store: Bengaluru, Category: Electronics


In [106]:
# Question 80: Bottom Three Profits
# Find the three lowest profit values in the profit matrix.

flat_indices = np.argsort(profit_data.ravel())[:3]

for idx in flat_indices:
    i, j = np.unravel_index(idx, profit_data.shape)
    print(f"Profit: ₹{profit_data[i,j]}, Store: {stores[i]}, Category: {categories[j]}")

Profit: ₹55000, Store: Pune, Category: Furniture
Profit: ₹60000, Store: Pune, Category: Sports
Profit: ₹60000, Store: Chennai, Category: Sports


# Part 14: Statistical Analysis

In [107]:
# Question 81: Sales Statistics
# Calculate the following for the complete sales array:

# Minimum
# Maximum
# Mean
# Median
# Standard deviation
# Variance
# 25th percentile
# 50th percentile
# 75th percentile

print("Minimum:", np.min(sales_data))
print("Maximum:", np.max(sales_data))
print("Mean:", np.mean(sales_data))
print("Median:", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))
print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


In [108]:
# Question 82: Store-Wise Standard Deviation
# Calculate the sales standard deviation for every store.

# Use this value to determine which store has the most variation between product categories.

store_std = np.std(sales_data, axis=1)

for i in range(len(stores)):
    print(stores[i], round(store_std[i], 2))

print("Most variation:", stores[np.argmax(store_std)])

Bengaluru 223059.53
Hyderabad 194502.57
Chennai 249265.59
Mumbai 271860.87
Pune 177200.45
Most variation: Mumbai


In [109]:
# Question 83: Category-Wise Standard Deviation
# Determine which product category has the highest variation in sales across stores.

category_std = np.std(sales_data, axis=0)

for i in range(len(categories)):
    print(categories[i], round(category_std[i], 2))

print("Highest variation:", categories[np.argmax(category_std)])

Electronics 122539.79
Groceries 43312.82
Clothing 33911.65
Furniture 41303.75
Beauty 26570.66
Sports 29832.87
Highest variation: Electronics


In [110]:
# Question 84: Sales Above Company Average
# Calculate the company-wide average sales value.

# Count how many store-category sales values are above this average.

company_average = np.mean(sales_data)
above_average = sales_data > company_average

print("Company Average Sales:", company_average)
print("Count Above Average:", np.sum(above_average))

Company Average Sales: 389166.6666666667
Count Above Average: 10


In [111]:
# Question 85: Outlier Detection
# Treat any sales value greater than:

# Mean + 1.5 × Standard Deviation
# as a high-value outlier.

# Identify all such sales values.

mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

threshold = mean_sales + 1.5 * std_sales
outlier_mask = sales_data > threshold

print("Threshold:", threshold)

for i, j in zip(*np.where(outlier_mask)):
    print(f"Store: {stores[i]}, Category: {categories[j]}, Sales: ₹{sales_data[i, j]}")

Threshold: 734650.4759833985
Store: Bengaluru, Category: Electronics, Sales: ₹850000
Store: Hyderabad, Category: Electronics, Sales: ₹780000
Store: Chennai, Category: Electronics, Sales: ₹920000
Store: Mumbai, Category: Electronics, Sales: ₹1050000


# Part 15: Reshaping and Transformation

In [113]:
# Question 86: Flatten Sales Data
# Convert the two-dimensional sales array into a one-dimensional array using:

# flatten()
# ravel()
# Explain the difference between the two methods.

sales_flatten = sales_data.flatten()
sales_ravel = sales_data.ravel()

print("Using flatten():", sales_flatten)
print("\nUsing ravel():", sales_ravel)


# Flatten creates a copy and it wont changes the original data (safe copy)
  # Ex: a = sales_data.flatten()
      # a[0] = 999
      # print(sales_data[0, 0]) It wont change the original data

# Ravel The original array may be changed, because ravel() usually returns a view of the original array.
  # Ex: a = sales_data.ravel() (memory efficient)
      # a[0] = 999

Using flatten(): [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Using ravel(): [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [115]:
# Question 87: Reshape Sales Data
# Reshape the 5 × 6 sales array into:

# 3 × 10
# 10 × 3
# 2 × 15
# 15 × 2
# Verify that no data is lost.

print("Original sales_data shape:", sales_data.shape)
print("Original sales_data size:", sales_data.size)

sales_3x10 = sales_data.reshape(3, 10)
sales_10x3 = sales_data.reshape(10, 3)
sales_2x15 = sales_data.reshape(2, 15)
sales_15x2 = sales_data.reshape(15, 2)


print("\nreshape data 3X10:")
print(sales_3x10)
print("shape:",sales_3x10.shape)
print("size:",sales_3x10.size)

print("\nreshape data 10X3:")
print(sales_10x3)
print("shape:",sales_10x3.shape)
print("size:",sales_10x3.size)

print("\nreshape data 2x15:")
print(sales_2x15)
print("shape:",sales_2x15.shape)
print("size:",sales_2x15.size)

print("\nreshape data 15X2:")
print(sales_15x2)
print("shape:",sales_15x2.shape)
print("size:",sales_15x2.size)

if (sales_data.size == sales_3x10.size and
    sales_data.size == sales_10x3.size and
    sales_data.size == sales_2x15.size and
    sales_data.size == sales_15x2.size):
    print("\nVerification: No data was lost during reshaping.")
else:
    print("\nVerification: Data loss detected during reshaping.")

Original sales_data shape: (5, 6)
Original sales_data size: 30

reshape data 3X10:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
shape: (3, 10)
size: 30

reshape data 10X3:
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
shape: (10, 3)
size: 30

reshape data 2x15:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
shape: (2, 15)
size: 30

reshape data 15X2:
[[ 8500

In [119]:
# Question 88: Transpose Sales Data
# Transpose the sales array so that:

# Rows represent product categories
# Columns represent stores
# Display the new shape.

sales_transposed = sales_data.T

print("Transposed data:",sales_transposed)
print("\nNew shape:", sales_transposed.shape)

Transposed data: [[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]

New shape: (6, 5)


In [122]:
# Question 89: Combined Sales and Cost Array
# Stack sales_data and cost_data vertically.

# Display the resulting shape.

combined_data = np.vstack((sales_data, cost_data))

print("combined_data:")
print(combined_data)
print("\nShape:", combined_data.shape)

combined_data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]

Shape: (10, 6)


In [123]:
# Question 90: Store-Level Combined Data
# Create a three-dimensional array where:

# First layer contains sales data
# Second layer contains cost data
# Use np.stack().

# Display the shape of the new array.

combined_3d = np.stack((sales_data, cost_data))

print("combined_3d:")
print(combined_3d)
print("\nShape:", combined_3d.shape)

combined_3d:
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]

Shape: (2, 5, 6)


# Part 16: Missing Data Scenario

In [124]:
# The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

print(sales_with_missing)

[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]


In [130]:
# Question 91: Missing Value Detection
# Find:

# Total number of missing values
# Location of missing values
# Stores and categories containing missing values

missing_mask = np.isnan(sales_with_missing)
missing_locations = np.argwhere(missing_mask)

print("Total missing values:", np.sum(missing_mask))

print("\nLocations of missing values (row, column indices):\n", missing_locations)

print("\nStores and categories containing missing values:")
for i, j in missing_locations:
    print(f"Store: {stores[i]}, Category: {categories[j]}")

Total missing values: 4

Locations of missing values (row, column indices):
 [[0 2]
 [1 3]
 [3 1]
 [4 4]]

Stores and categories containing missing values:
Store: Bengaluru, Category: Clothing
Store: Hyderabad, Category: Furniture
Store: Mumbai, Category: Groceries
Store: Pune, Category: Beauty


In [131]:
# Question 92: Replace Missing Values with Zero
# Replace all missing sales values with zero.

sales_filled = np.nan_to_num(sales_with_missing, nan=0)

print(sales_filled)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [133]:
# Question 93: Replace with Company Average
# Replace missing values with the overall average of available sales values.

# Use np.nanmean().

average_sales = np.nanmean(sales_with_missing)
sales_filled = np.where(np.isnan(sales_with_missing), average_sales, sales_with_missing)

print("Average Sales:", average_sales)
print("\nsales filled:")
print(sales_filled)

Average Sales: 398846.1538461539

sales filled:
[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


In [134]:
# Question 94: Replace with Category Average
# Replace each missing value with the average sales value of its respective product category.

category_avg = np.nanmean(sales_with_missing, axis=0)
sales_filled = np.where(np.isnan(sales_with_missing), category_avg, sales_with_missing)

print("Category Averages:", category_avg)
print("\nsales filled:")
print(sales_filled)

Category Averages: [858000. 418750. 322500. 276250. 208750. 235000.]

sales filled:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [137]:
# Question 95: Missing Value Impact
# Compare total sales before and after replacing missing values with zero.

total_before = np.nansum(sales_with_missing)
sales_zero = np.nan_to_num(sales_with_missing, nan=0)
total_after = np.sum(sales_zero)

print("Original Sales Data:")
print(sales_with_missing)

print("\nSales Data After Replacing Missing Values with 0:")
print(sales_zero)

print("\nTotal Before:", total_before)
print("Total After:", total_after)
print("Difference:", total_before - total_after)

Original Sales Data:
[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]

Sales Data After Replacing Missing Values with 0:
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]

Total Before: 10370000.0
Total After: 10370000.0
Difference: 0.0


# Part 17: Conditional Business Decisions

In [140]:
# Question 96: Store Performance Labels
# Classify each store based on total sales:

# "Excellent": Total sales above ₹28,00,000
# "Good": Total sales between ₹24,00,000 and ₹28,00,000
# "Needs Improvement": Total sales below ₹24,00,000
# Use np.select().

store_sales = np.sum(sales_data, axis=1)

conditions = [
    store_sales > 2800000,
    (store_sales >= 2400000) & (store_sales <= 2800000),
    store_sales < 2400000
]

labels = ["Excellent", "Good", "Needs Improvement"]

performance = np.select(conditions, labels, default='Unknown')

for i in range(len(stores)):
    print(stores[i], store_sales[i], performance[i])

Bengaluru 2270000 Needs Improvement
Hyderabad 2295000 Needs Improvement
Chennai 2310000 Needs Improvement
Mumbai 2820000 Excellent
Pune 1980000 Needs Improvement


In [144]:
# Question 97: Profitability Classification
# Classify each store-category combination as:

# "Highly Profitable": Profit above ₹2,00,000
# "Profitable": Profit between ₹1,00,000 and ₹2,00,000
# "Low Profit": Profit below ₹1,00,000
# "Loss": Profit below zero

conditions = [
    profit_data > 200000,
    (profit_data >= 100000) & (profit_data <= 200000),
    (profit_data >= 0) & (profit_data < 100000),
    profit_data < 0
]

labels = ["Highly Profitable", "Profitable", "Low Profit", "Loss"]

profit_class = np.select(conditions, labels, default='unknown')

print(profit_class)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [145]:
# Question 98: Expansion Recommendation
# A store is eligible for expansion when:

# Total sales are above ₹25,00,000
# Total profit is above ₹7,00,000
# Overall profit margin is above 25%
# Identify eligible stores.

total_sales = np.sum(sales_data, axis=1)
total_profit = np.sum(profit_data, axis=1)
profit_margin = (total_profit / total_sales) * 100

eligible = (total_sales > 2500000) & (total_profit > 700000) & (profit_margin > 25)

for i in np.where(eligible)[0]:
    print(f"Store: {stores[i]}")
    print(f"Sales: ₹{total_sales[i]}")
    print(f"Profit: ₹{total_profit[i]}")
    print(f"Profit Margin: {profit_margin[i]:.2f}%")

Store: Mumbai
Sales: ₹2820000
Profit: ₹755000
Profit Margin: 26.77%


In [146]:
# Question 99: Category Promotion Recommendation
# A product category should receive additional promotion when:

# Average sales are below ₹3,00,000
# Profit margin is above 25%
# Identify the categories that satisfy these conditions.

avg_sales = np.mean(sales_data, axis=0)
category_profit = np.sum(profit_data, axis=0)
category_margin = (category_profit / np.sum(sales_data, axis=0)) * 100

promotion = (avg_sales < 300000) & (category_margin > 25)

for i in np.where(promotion)[0]:
    print(f"Category: {categories[i]}")
    print(f"Average Sales: ₹{avg_sales[i]:.2f}")
    print(f"Profit Margin: {category_margin[i]:.2f}%")

Category: Furniture
Average Sales: ₹283000.00
Profit Margin: 26.15%
Category: Beauty
Average Sales: ₹202000.00
Profit Margin: 34.16%
Category: Sports
Average Sales: ₹235000.00
Profit Margin: 28.94%


In [147]:
# Question 100: Cost Optimization Recommendation
# Find store-category combinations where:

# Cost is greater than ₹2,50,000
# Profit margin is below 25%
# These combinations should be reviewed for cost optimization.

profit_margin = (profit_data / sales_data) * 100

mask = (cost_data > 250000) & (profit_margin < 25)

for i, j in zip(*np.where(mask)):
    print(f"Store: {stores[i]}, Category: {categories[j]}, "
          f"Cost: ₹{cost_data[i,j]}, Profit Margin: {profit_margin[i,j]:.2f}%")

Store: Bengaluru, Category: Electronics, Cost: ₹640000, Profit Margin: 24.71%
Store: Hyderabad, Category: Electronics, Cost: ₹590000, Profit Margin: 24.36%
Store: Hyderabad, Category: Groceries, Cost: ₹350000, Profit Margin: 23.91%
Store: Chennai, Category: Electronics, Cost: ₹700000, Profit Margin: 23.91%
Store: Chennai, Category: Groceries, Cost: ₹295000, Profit Margin: 24.36%
Store: Mumbai, Category: Electronics, Cost: ₹790000, Profit Margin: 24.76%
Store: Mumbai, Category: Groceries, Cost: ₹390000, Profit Margin: 23.53%
Store: Pune, Category: Electronics, Cost: ₹530000, Profit Margin: 23.19%
Store: Pune, Category: Groceries, Cost: ₹310000, Profit Margin: 23.46%


# Part 18: Inventory Scenario

In [148]:
# Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

print(opening_stock)
print(units_sold)

[[120 450 300  90 250 180]
 [110 500 280 100 270 200]
 [130 420 320  85 240 170]
 [150 550 350 120 300 220]
 [100 400 260  75 220 160]]
[[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


In [149]:
# Question 101: Closing Stock
# Calculate closing stock using:

# Closing Stock = Opening Stock - Units Sold

closing_stock = opening_stock - units_sold

print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [150]:
# Question 102: Low-Stock Identification
# Identify store-category combinations where closing stock is below 30 units.

low_stock = closing_stock < 30

for i, j in zip(*np.where(low_stock)):
    print(f"Store: {stores[i]}, Category: {categories[j]}, Closing Stock: {closing_stock[i,j]}")

Store: Bengaluru, Category: Electronics, Closing Stock: 25
Store: Bengaluru, Category: Furniture, Closing Stock: 25
Store: Hyderabad, Category: Electronics, Closing Stock: 25
Store: Hyderabad, Category: Furniture, Closing Stock: 25
Store: Chennai, Category: Electronics, Closing Stock: 25
Store: Chennai, Category: Furniture, Closing Stock: 25
Store: Mumbai, Category: Electronics, Closing Stock: 25
Store: Pune, Category: Electronics, Closing Stock: 25
Store: Pune, Category: Furniture, Closing Stock: 20


In [151]:
# Question 103: Stock Availability Percentage
# Calculate the percentage of opening stock that remains unsold.

availability_percentage = (closing_stock / opening_stock) * 100

print(availability_percentage)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


In [152]:
# Question 104: Fast-Moving Products
# A product is considered fast-moving when more than 80% of its opening stock has been sold.

# Identify fast-moving store-category combinations.

sold_percentage = (units_sold / opening_stock) * 100
fast_moving = sold_percentage > 80

for i, j in zip(*np.where(fast_moving)):
    print(f"Store: {stores[i]}, Category: {categories[j]}, Sold: {sold_percentage[i,j]:.2f}%")

Store: Bengaluru, Category: Groceries, Sold: 84.44%
Store: Hyderabad, Category: Groceries, Sold: 84.00%
Store: Hyderabad, Category: Clothing, Sold: 82.14%
Store: Chennai, Category: Electronics, Sold: 80.77%
Store: Chennai, Category: Groceries, Sold: 83.33%
Store: Chennai, Category: Clothing, Sold: 84.38%
Store: Mumbai, Category: Electronics, Sold: 83.33%
Store: Mumbai, Category: Groceries, Sold: 85.45%
Store: Mumbai, Category: Clothing, Sold: 84.29%
Store: Pune, Category: Groceries, Sold: 82.50%


In [153]:
# Question 105: Category-Wise Units Sold
# Calculate the total units sold for each product category.

category_units_sold = np.sum(units_sold, axis=0)

for i in range(len(categories)):
    print(f"{categories[i]}: {category_units_sold[i]} units")

Electronics: 485 units
Groceries: 1950 units
Clothing: 1240 units
Furniture: 345 units
Beauty: 980 units
Sports: 720 units


In [154]:
# Question 106: Store-Wise Units Sold
# Calculate total units sold by each store.

store_units_sold = np.sum(units_sold, axis=1)

for i in range(len(stores)):
    print(f"{stores[i]}: {store_units_sold[i]} units")

Bengaluru: 1110 units
Hyderabad: 1175 units
Chennai: 1095 units
Mumbai: 1390 units
Pune: 950 units


In [155]:
# Question 107: Best Store by Unit Sales
# Identify the store that sold the highest total number of units.

store_units_sold = np.sum(units_sold, axis=1)

best_index = np.argmax(store_units_sold)

print("Best Store:", stores[best_index])
print("Units Sold:", store_units_sold[best_index])

Best Store: Mumbai
Units Sold: 1390


In [156]:
# Question 108: Reorder Requirement
# A store should reorder a category when closing stock is below 25 units.

# Create a Boolean reorder matrix.

reorder_matrix = closing_stock < 25

print(reorder_matrix)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [157]:
# Question 109: Reorder Quantity
# Assume each category must maintain 100 units after reordering.

# Calculate reorder quantities only for combinations where closing stock is below 25.

# For all other combinations, return zero.

reorder_quantity = np.where(closing_stock < 25, 100 - closing_stock, 0)

print("Reorder Quantity:")
print(reorder_quantity)

Reorder Quantity:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


# Part 19: Advanced NumPy Questions

In [159]:
# Question 110: Cumulative Store Sales
# Calculate cumulative category sales for each store using np.cumsum().

print(sales_data)

cumulative_sales = np.cumsum(sales_data, axis=1)
print("\ncumulative_sales:")
print(cumulative_sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

cumulative_sales:
[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [160]:
# Question 111: Cumulative Company Sales
# Flatten the sales array and calculate cumulative company sales.

flat_sales = sales_data.flatten()
cumulative_company_sales = np.cumsum(flat_sales)

print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [161]:
# Question 112: Sales Difference Between Categories
# Calculate the difference between consecutive category sales for each store using np.diff().

sales_difference = np.diff(sales_data, axis=1)

print(sales_difference)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [162]:
# Question 113: Unique Sales Values
# Find all unique sales values in sales_data.

# Also count the frequency of each value.

unique_values, frequencies = np.unique(sales_data, return_counts=True)

print("Unique Sales Values:")
print(unique_values)

print("\nFrequency of Each Value:")
for value, count in zip(unique_values, frequencies):
    print(f"₹{value}: {count}")

Unique Sales Values:
[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]

Frequency of Each Value:
₹175000: 1
₹185000: 1
₹190000: 1
₹205000: 1
₹210000: 1
₹215000: 1
₹225000: 2
₹240000: 1
₹250000: 1
₹260000: 1
₹275000: 1
₹280000: 1
₹290000: 1
₹295000: 1
₹310000: 2
₹340000: 1
₹345000: 1
₹375000: 1
₹390000: 1
₹405000: 1
₹420000: 1
₹460000: 1
₹510000: 1
₹690000: 1
₹780000: 1
₹850000: 1
₹920000: 1
₹1050000: 1


In [164]:
# Question 114: Search for Specific Sales
# Check whether the value ₹4,20,000 exists in the sales array.

# Return its location.

indices = np.where(sales_data == 420000)

print("Locations:", indices)

Locations: (array([0]), array([1]))


In [165]:
# Question 115: Compare Sales and Cost
# Create a Boolean array showing whether sales are greater than cost for every combination.

# Verify whether all combinations are profitable using np.all().

profitable = sales_data > cost_data

print("Sales > Cost:")
print(profitable)

print("All combinations are profitable:", np.all(profitable))

Sales > Cost:
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All combinations are profitable: True


In [166]:
# Question 116: Clip Profit Values
# For reporting purposes, management wants profit values limited to:

# Minimum: ₹75,000
# Maximum: ₹2,50,000
# Use np.clip() to create a reporting profit array.

reporting_profit = np.clip(profit_data, 75000, 250000)

print("Original Profit:")
print(profit_data)

print("\nReporting Profit:")
print(reporting_profit)

Original Profit:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]

Reporting Profit:
[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [167]:
# Question 117: Normalize Sales Data
# Normalize all sales values using min-max normalization:

# Normalized Sales =
# (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

min_sales = np.min(sales_data)
max_sales = np.max(sales_data)

normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)

print("Normalized Sales:")
print(normalized_sales)

Normalized Sales:
[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [168]:
# Question 118: Standardize Sales Data
# Standardize sales using:

# Standardized Sales =
# (Sales - Mean Sales) / Standard Deviation

mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

standardized_sales = (sales_data - mean_sales) / std_sales

print("Mean Sales:", mean_sales)
print("Standard Deviation:", std_sales)

print("\nStandardized Sales:")
print(standardized_sales)

Mean Sales: 389166.6666666667
Standard Deviation: 230322.53954448793

Standardized Sales:
[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [169]:
# Question 119: Round Values
# Convert profit margin values into:

# Two decimal places
# Nearest whole number
# Floor values
# Ceiling values

profit_margin = (profit_data / sales_data) * 100

two_decimal = np.round(profit_margin, 2)
whole_number = np.round(profit_margin)
floor_value = np.floor(profit_margin)
ceiling_value = np.ceil(profit_margin)

print("Two Decimal Places:")
print(two_decimal)

print("\nNearest Whole Number:")
print(whole_number)

print("\nFloor Values:")
print(floor_value)

print("\nCeiling Values:")
print(ceiling_value)

Two Decimal Places:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Nearest Whole Number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Floor Values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Ceiling Values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [170]:
# Question 120: Save and Load Data
# Save the following arrays as NumPy binary files:

# sales_data.npy
# cost_data.npy
# profit_data.npy
# Load them back and verify that the loaded arrays are equal to the original arrays.

np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

sales_loaded = np.load("sales_data.npy")
cost_loaded = np.load("cost_data.npy")
profit_loaded = np.load("profit_data.npy")

print("Sales equal:", np.array_equal(sales_data, sales_loaded))
print("Cost equal:", np.array_equal(cost_data, cost_loaded))
print("Profit equal:", np.array_equal(profit_data, profit_loaded))

Sales equal: True
Cost equal: True
Profit equal: True


# Part 20: Final Retail Analytics Project

In [171]:
# Prepare a complete NumPy-based retail performance report.

# Your report must contain the following information:

# Company Summary

# Total company sales
# Total company cost
# Total company profit
# Overall company profit margin
# Average transaction value
# Highest individual sales value
# Lowest individual sales value

# Store Summary
# For every store, display:

# Total sales
# Total cost
# Total profit
# Profit margin
# Number of category targets achieved
# Total units sold
# Expansion eligibility

# Category Summary
# For every category, display:

# Total sales
# Total cost
# Total profit
# Profit margin
# Average sales
# Number of stores achieving the target
# Total units sold

# Management Recommendations
# Based on the analysis, identify:

# Best-performing store
# Lowest-performing store
# Most profitable category
# Lowest-profit category
# Store recommended for expansion
# Category requiring additional marketing
# Store-category combinations needing cost optimization
# Store-category combinations requiring inventory reorder


# Expected Final Output Format
# SMARTMART RETAIL PERFORMANCE REPORT
# ===================================

# COMPANY SUMMARY
# ---------------
# Total Sales:
# Total Cost:
# Total Profit:
# Overall Profit Margin:

# BEST-PERFORMING STORE
# ---------------------
# Store:
# Sales:
# Cost:
# Profit:
# Profit Margin:

# MOST PROFITABLE CATEGORY
# ------------------------
# Category:
# Sales:
# Cost:
# Profit:
# Profit Margin:

# EXPANSION RECOMMENDATIONS
# -------------------------
# Eligible Stores:

# COST OPTIMIZATION
# -----------------
# Store:
# Category:
# Cost:
# Profit Margin:

# INVENTORY REORDER
# -----------------
# Store:
# Category:
# Closing Stock:
# Reorder Quantity:



import numpy as np

# ==============================
# CALCULATIONS
# ==============================

# Company calculations
total_sales = np.sum(sales_data)
total_cost = np.sum(cost_data)
total_profit = np.sum(profit_data)

overall_profit_margin = (total_profit / total_sales) * 100
average_transaction = np.mean(sales_data)

highest_sales = np.max(sales_data)
lowest_sales = np.min(sales_data)


# Store calculations
store_sales = np.sum(sales_data, axis=1)
store_cost = np.sum(cost_data, axis=1)
store_profit = np.sum(profit_data, axis=1)

store_margin = (store_profit / store_sales) * 100

target_achieved = sales_data >= sales_targets
target_count = np.sum(target_achieved, axis=1)

store_units = np.sum(units_sold, axis=1)

expansion = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_margin > 25)
)


# Category calculations
category_sales = np.sum(sales_data, axis=0)
category_cost = np.sum(cost_data, axis=0)
category_profit = np.sum(profit_data, axis=0)

category_margin = (category_profit / category_sales) * 100
category_avg_sales = np.mean(sales_data, axis=0)

category_target_count = np.sum(target_achieved, axis=0)
category_units = np.sum(units_sold, axis=0)


# Marketing recommendation
marketing = (
    (category_avg_sales < 300000) &
    (category_margin > 25)
)


# Cost optimization
profit_margin = (profit_data / sales_data) * 100

cost_optimization = (
    (cost_data > 250000) &
    (profit_margin < 25)
)


# Inventory reorder
reorder = closing_stock < 25
reorder_quantity = np.where(reorder, 100 - closing_stock, 0)


# ==============================
# SMARTMART REPORT
# ==============================

print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")


# COMPANY SUMMARY
print("\nCOMPANY SUMMARY")
print("---------------")
print(f"Total Sales: ₹{total_sales}")
print(f"Total Cost: ₹{total_cost}")
print(f"Total Profit: ₹{total_profit}")
print(f"Overall Profit Margin: {overall_profit_margin:.2f}%")
print(f"Average Transaction Value: ₹{average_transaction:.2f}")
print(f"Highest Individual Sales: ₹{highest_sales}")
print(f"Lowest Individual Sales: ₹{lowest_sales}")


# STORE SUMMARY
print("\nSTORE SUMMARY")
print("-------------")

for i in range(len(stores)):
    status = "Yes" if expansion[i] else "No"

    print(f"\nStore: {stores[i]}")
    print(f"Total Sales: ₹{store_sales[i]}")
    print(f"Total Cost: ₹{store_cost[i]}")
    print(f"Total Profit: ₹{store_profit[i]}")
    print(f"Profit Margin: {store_margin[i]:.2f}%")
    print(f"Targets Achieved: {target_count[i]}")
    print(f"Total Units Sold: {store_units[i]}")
    print(f"Expansion Eligible: {status}")


# CATEGORY SUMMARY
print("\nCATEGORY SUMMARY")
print("----------------")

for i in range(len(categories)):
    print(f"\nCategory: {categories[i]}")
    print(f"Total Sales: ₹{category_sales[i]}")
    print(f"Total Cost: ₹{category_cost[i]}")
    print(f"Total Profit: ₹{category_profit[i]}")
    print(f"Profit Margin: {category_margin[i]:.2f}%")
    print(f"Average Sales: ₹{category_avg_sales[i]:.2f}")
    print(f"Stores Achieving Target: {category_target_count[i]}")
    print(f"Total Units Sold: {category_units[i]}")


# ==============================
# MANAGEMENT RECOMMENDATIONS
# ==============================

# Best and lowest performing store
best_store_index = np.argmax(store_profit)
lowest_store_index = np.argmin(store_profit)

# Most and least profitable category
best_category_index = np.argmax(category_profit)
lowest_category_index = np.argmin(category_profit)


print("\nMANAGEMENT RECOMMENDATIONS")
print("==========================")

# Best store
print("\n1. BEST-PERFORMING STORE")
print("------------------------")
print(f"Store: {stores[best_store_index]}")
print(f"Sales: ₹{store_sales[best_store_index]}")
print(f"Cost: ₹{store_cost[best_store_index]}")
print(f"Profit: ₹{store_profit[best_store_index]}")
print(f"Profit Margin: {store_margin[best_store_index]:.2f}%")


# Lowest store
print("\n2. LOWEST-PERFORMING STORE")
print("--------------------------")
print(f"Store: {stores[lowest_store_index]}")
print(f"Sales: ₹{store_sales[lowest_store_index]}")
print(f"Profit: ₹{store_profit[lowest_store_index]}")


# Most profitable category
print("\n3. MOST PROFITABLE CATEGORY")
print("---------------------------")
print(f"Category: {categories[best_category_index]}")
print(f"Sales: ₹{category_sales[best_category_index]}")
print(f"Cost: ₹{category_cost[best_category_index]}")
print(f"Profit: ₹{category_profit[best_category_index]}")
print(f"Profit Margin: {category_margin[best_category_index]:.2f}%")


# Lowest-profit category
print("\n4. LOWEST-PROFIT CATEGORY")
print("-------------------------")
print(f"Category: {categories[lowest_category_index]}")
print(f"Profit: ₹{category_profit[lowest_category_index]}")


# Expansion
print("\n5. EXPANSION RECOMMENDATIONS")
print("----------------------------")

eligible_stores = np.where(expansion)[0]

if len(eligible_stores) == 0:
    print("No stores are eligible for expansion.")
else:
    for i in eligible_stores:
        print(f"Store: {stores[i]}")


# Marketing
print("\n6. CATEGORY REQUIRING ADDITIONAL MARKETING")
print("------------------------------------------")

marketing_categories = np.where(marketing)[0]

for i in marketing_categories:
    print(f"Category: {categories[i]}")


# Cost optimization
print("\n7. COST OPTIMIZATION")
print("--------------------")

cost_indices = np.where(cost_optimization)

for i, j in zip(cost_indices[0], cost_indices[1]):
    print(f"Store: {stores[i]}")
    print(f"Category: {categories[j]}")
    print(f"Cost: ₹{cost_data[i,j]}")
    print(f"Profit Margin: {profit_margin[i,j]:.2f}%")
    print()


# Inventory reorder
print("\n8. INVENTORY REORDER")
print("--------------------")

reorder_indices = np.where(reorder)

for i, j in zip(reorder_indices[0], reorder_indices[1]):
    print(f"Store: {stores[i]}")
    print(f"Category: {categories[j]}")
    print(f"Closing Stock: {closing_stock[i,j]}")
    print(f"Reorder Quantity: {reorder_quantity[i,j]}")
    print()

SMARTMART RETAIL PERFORMANCE REPORT

COMPANY SUMMARY
---------------
Total Sales: ₹11675000
Total Cost: ₹8600000
Total Profit: ₹3075000
Overall Profit Margin: 26.34%
Average Transaction Value: ₹389166.67
Highest Individual Sales: ₹1050000
Lowest Individual Sales: ₹175000

STORE SUMMARY
-------------

Store: Bengaluru
Total Sales: ₹2270000
Total Cost: ₹1665000
Total Profit: ₹605000
Profit Margin: 26.65%
Targets Achieved: 1
Total Units Sold: 1110
Expansion Eligible: No

Store: Hyderabad
Total Sales: ₹2295000
Total Cost: ₹1685000
Total Profit: ₹610000
Profit Margin: 26.58%
Targets Achieved: 4
Total Units Sold: 1175
Expansion Eligible: No

Store: Chennai
Total Sales: ₹2310000
Total Cost: ₹1710000
Total Profit: ₹600000
Profit Margin: 25.97%
Targets Achieved: 2
Total Units Sold: 1095
Expansion Eligible: No

Store: Mumbai
Total Sales: ₹2820000
Total Cost: ₹2065000
Total Profit: ₹755000
Profit Margin: 26.77%
Targets Achieved: 6
Total Units Sold: 1390
Expansion Eligible: Yes

Store: Pune
Total 